### PR TITLE
Converted translation system to Gettext

### PR DESCRIPTION
**Pull request by gunchleoc**
There were some issues with the translations, e.g. changes in the English strings that the translators couldn't notice and didn't fix, and obsolete strings that wouldn't need translating anymore. Also adding, new strings was quite unwieldy.

So, I decided to try my hand at switching ths translation system over to Gettext. This has the additional advantage that translators can use all kinds of nifty translation tools.

There is quite a bit of string converting going on in this branch due to the ways that SFML handles strings. I can't initialize the SFML srings with a locale, because the desired locale might not be available on the system. So, toAnsiString is not usable...

This has been tested on Ubuntu and MinGW64.

### CODE REVIEW

**Comment by joedf** [comment]
It's seems to me, that they might have abandoned the project or something. Unless, the author is simply too busy for the moment. However, it seems to me that he has had recent activity. https://github.com/thelaui?tab=activity

**Comment by gunchleoc** [comment]
Well, interests shift over time. If I don't hear from him in a while, I'll just give him a poke - maybe he would be willing to give somebody else access to the repro to continue working on this.

**Comment by joedf** [comment]
Agreed. :)

**Comment by eXpl0it3r** [comment]
This was closed due to history rewrite to include the SVN history.

I'll grab the commits later on and recreate a new PR. 
It's a feature that needs some more thinking, so priority-wise I first try to get the repository updated and properly building again.

**Pull request closed without merging**
