### PR TITLE
Updated shader code.

### PR DESCRIPTION
**Pull request by gunchleoc**
The code didn't compile on my machine, so I updated the shader function calls a bit - I don't know if any CMake adjustments would be necessary.

### CODE REVIEW

**Comment by carstene1ns** [comment]
This looks the same like a combination of the open Pull Requests #3 and #17.

**Comment by gunchleoc** [comment]
You're right, it actually is.

**Comment by carstene1ns** [comment]
No idea, development of this project seems to have stalled.

**Comment by eXpl0it3r** [comment]
This was closed due to history rewrite to include the SVN history.

Parts of it was also already implemented with other merged PRs, so I'll look into what is still remains to be done.

**Comment by eXpl0it3r** [comment]
Integrated your additional changes with the commit 474735712cc0851968ea8f08289d9702487c9e70

**Pull request closed without merging**
